/*
**  SONY CONFIDENTIAL MATERIAL. DO NOT DISTRIBUTE.
**  SNEI Trilithium
**  Copyright (C) 2009-2010 Sony Corporation
**  All Rights Reserved
*/
/*! @file fpAlphaFadeAB.cg

*/

float4 main(float4 tc : TEXCOORD0,
            uniform float alpha = 1,
            uniform sampler2D textureA,
            uniform sampler2D textureB,
            uniform float fade = 1): COLOR
{
    return ( tex2D(textureA,tc.xy) * (1-fade) + tex2D(textureB,tc.zw) * fade ) * alpha;
}

